<?php

/**
 * @file
 * Module file for the entity tokens module.
 */

/**
 * Implements hook_field_info_alter().
 */
function entity_token_field_info_alter(&$info) {
  foreach (array('date', 'datetime', 'datestamp') as $date_type) {
    if (isset($info[$date_type])) {
      $info[$date_type]['property_type'] = 'date';
      $info[$date_type]['property_callbacks'][] = 'date_entity_metadata_property_info_alter';
    }
  }
}

/**
 * Returns a metadata wrapper for accessing site-wide properties.
 *
 * Although there is no 'site' entity or such, modules may provide info about
 * site-wide properties using hook_entity_property_info(). This function returns
 * a wrapper for making use of this properties.
 *
 * @return EntityMetadataWrapper
 *   A wrapper for accessing site-wide properties.
 *
 * @see entity_metadata_system_entity_property_info()
 */
function entity_token_metadata_site_wrapper() {
  $site_info = entity_plus_get_property_info('site');
  $info['property info'] = $site_info['properties'];
  return entity_metadata_wrapper('site', FALSE, $info);
}
